[package]
name = "ftdi-hal"
version = "0.1.0"
edition = "2024"

[dependencies]
eh1 = { package = "embedded-hal", version = "1" }
log = "0.4.27"
nusb = "0.1.14"
thiserror = "2.0.12"
tokio = {version="1.46.0",features=["rt","rt-multi-thread","macros","time"]}

[dev-dependencies]
itertools = "0.14.0"
